# Generated by Django 3.1.6 on 2021-03-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volcanoe',
            name='elevation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
