# Generated by Django 3.1.6 on 2021-03-19 01:38

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path

DATA_FILENAME = 'data.json'
def load_data(apps, schema_editor):
    Volcanoe = apps.get_model('volcanoes', 'Volcanoe')
    jsonfile = Path(__file__).parents[2] / DATA_FILENAME

    with open(str(jsonfile)) as datafile:
        objects = json.load(datafile)
        for obj in objects['features']:
            try:
                objType = obj['type']
                if objType == 'Feature':
                    properties = obj['properties']
                    name = properties.get('NAME_')
                    country = properties.get('LOCATION')
                    elevation = properties.get('ELEV')
                    longitude = properties.get('LON', 0)
                    latitude = properties.get('LAT', 0)
                    location = fromstr(f'POINT({longitude} {latitude})', srid=4326)
                    Volcanoe(name=name, location = location, country = country, elevation = elevation).save()
            except KeyError:
                pass 


class Migration(migrations.Migration):

    dependencies = [
        ('volcanoes', '0002_auto_20210319_0138'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
